output "ec2-private-key-pem" {
  description = "EC2 SSH key generated by terraform"
  value       = tls_private_key.rsa.private_key_pem
  sensitive   = true
}

output "public_ip" {
  description = "Public DNS of Application EC2 server"
  value       = aws_instance.app-server.public_dns
}

output "app_sg" {
  description = "Application EC2 instance security group"
  value       = aws_security_group.app-sg
}