# Specify the image repository and tag
image:
  repository: staneja90/prehire-demo-go-app
  tag: v2

# Specify the number of replicas for the deployment
replicaCount: 1

# Specify the service port
service:
  port: 80
