apiVersion: apps/v1
kind: Deployment
metadata:
  name: secure-fastapi
  labels:
    app: secure-fastapi

spec:
  replicas: 2

  selector:
    matchLabels:
      app: secure-fastapi

  template:
    metadata:
      labels:
        app: secure-fastapi

    spec:
      containers:
        - name: secure-fastapi

          image: ghcr.io/laharika08/secure-ci-cd-final-demo:v1
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 8000

          env:
            - name: APP_VERSION
              value: "1.0.0"

            - name: BUILD_ID
              value: "demo-build"

            - name: DEPLOYMENT_ENV
              value: "production"

            - name: SECURITY_STATUS
              value: "pass"

            - name: BUILD_TIMESTAMP
              value: "2026-03-09T22:00:00"

          readinessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 20

          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"

            limits:
              cpu: "500m"
              memory: "512Mi"

---

apiVersion: v1
kind: Service

metadata:
  name: secure-fastapi

spec:
  type: ClusterIP

  selector:
    app: secure-fastapi

  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
      name: http
